
FROM mariadb:10.11

RUN apt-get update && apt-get install -y \
    procps \
    htop \
    less \
    vim \
    nano \
    tree \
    lsof \
    net-tools \
    iputils-ping \
    dnsutils \
    curl \
    rsync \
 && rm -rf /var/lib/apt/lists/*

