networks:
  default:
    ipam:
      config:
        - subnet: __NET_PREFIX__.0/24

services:

  db:
    build:
      context: ./mariadb
    container_name: __PROJECT___db
    hostname: db

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: __PROJECT__
      MYSQL_USER: __PROJECT__
      MYSQL_PASSWORD: __PROJECT__

    volumes:
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./data/mysql:/var/lib/mysql
      - ./mounted_shared_etc/hosts:/etc/hosts:ro

    ports:
      - "__MYSQL_PORT__:3306"

    networks:
      default:
        ipv4_address: __NET_PREFIX__.10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: __PROJECT___phpmyadmin
    hostname: phpmyadmin

    ports:
      - "__PMA_PORT__:80"

    environment:
      PMA_HOST: "db"
      PMA_USER: "__PROJECT__"
      PMA_PASSWORD: "__PROJECT__"

    volumes:
      - ./mounted_shared_etc/hosts:/etc/hosts:ro

    networks:
      default:
        ipv4_address: __NET_PREFIX__.11

    depends_on:
      - db
