services:

  pgdb:
    build:
      context: ./postgres
    container_name: __PROJECT___postgres_db

    environment:
      POSTGRES_USER: __PROJECT__
      POSTGRES_PASSWORD: __PROJECT__
      POSTGRES_DB: __PROJECT__

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    ports:
      - "__MYSQL_PORT__:5432"

  adminer:
    image: adminer:latest
    container_name: __PROJECT___adminer

    ports:
      - "__PMA_PORT__:8080"

    environment:
      ADMINER_DEFAULT_SERVER: pgdb

    depends_on:
      - pgdb
